Repository SOPKATHON-iOS-TEAM4/iOS, pull requests merged in 2024-05, with the labels that each got.

#7 [Setting/#5] 컬러 에셋 추가
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale10.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale20.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale30.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale40.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale5.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale50.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale60.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale70.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale80.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/Grayscale90.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Grayscale/White.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main10.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main20.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main30.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main40.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main5.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main50.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main60.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main70.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main80.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Main/Main90.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub10.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub20.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub30.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub40.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub5.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub50.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub60.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub70.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub80.colorset/Contents.json
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Resources/Assets.xcassets/Color/Sub/Sub90.colorset/Contents.json
Labels: Setting⚙️, 정빈🍔

#8 [Fix] #6 - FontLiterals 수정
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Global/Literals/FontLiterals.swift
Labels: Fix🔨, 가현🍒

#13 [Feat] #9 - 단어장 추가 View UI 구현
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4.xcodeproj/project.pbxproj
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/CreateTermList/View/CreateTermListView.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/CreateTermList/ViewController/CreateTermListViewController.swift
Labels: Feat🔥, 정빈🍔

#18 [Feat] #16 - 단어 추가 View UI 구현
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4.xcodeproj/project.pbxproj
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Network/Home/DTO/AddedTerm.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/Cell/AddedTermCell.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/View/AddTermView.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/ViewController/AddTermViewController.swift
Labels: Feat🔥, 정빈🍔

#31 [Feat] #21 - Interaction 구현
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/Cell/AddedTermCell.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/View/AddTermView.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/ViewController/AddTermViewController.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/CreateTermList/View/CreateTermListView.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/CreateTermList/ViewController/CreateTermListViewController.swift
Labels: Feat🔥, 정빈🍔

#35 [Feat] #33 - API 연결 및 네비게이션 바 설정
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/AddTerm/ViewController/AddTermViewController.swift
  Sopkathon_iOS_Team4/Sopkathon_iOS_Team4/Presentation/CreateTermList/ViewController/CreateTermListViewController.swift
Labels: Feat🔥, 정빈🍔
